apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: testkube-tests
 namespace: argocd
spec:
 project: default
 source:
   repoURL: https://github.com/techmaharaj/testkube-gitops.git
   targetRevision: HEAD
   path: postman-collection
   plugin:
     name: testkube
 destination:
   server: https://kubernetes.default.svc
   namespace: testkube
